export const PROFILE_CITY_MAX_LENGTH = 120;
export const PROFILE_HOLIDAY_LABEL_MAX_LENGTH = 120;
export const PROFILE_AVAILABILITY_NOTE_MAX_LENGTH = 500;

export const PROJECT_NAME_MAX_LENGTH = 200;
export const PROJECT_CLIENT_NAME_MAX_LENGTH = 200;
export const PROJECT_ADMIN_NOTES_MAX_LENGTH = 5000;

export const ENGINEER_SALARY_NOTES_MAX_LENGTH = 1000;

export const ADMIN_AUDIT_ACTOR_EMAIL_MAX_LENGTH = 320;
export const ADMIN_AUDIT_ACTION_MAX_LENGTH = 120;
export const ADMIN_AUDIT_TARGET_TYPE_MAX_LENGTH = 80;
export const ADMIN_AUDIT_TARGET_ID_MAX_LENGTH = 120;
export const ADMIN_AUDIT_SUMMARY_MAX_LENGTH = 500;
